### ISSUE TITLE
Actividad 2

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-f4#2]
[Uploading Practica 2.Equipo.pdf…]()

Gomez Hernandez Alyn Ximena
Claudia Yuliana Morales Hernández
Maria Lizbeth Bautista Garcia
Evelyn Sosa Jose

**Comment by LenninGS-0** [comment]
Portada: 25/25
Procedimiento:25/25
Figuras, ilustraciones y fotografías: 25/25
Resultados y conclusiones : 25/25
Total: 100

**Comment by josealfredo79** [comment]
[Uploading 22620040-infografia.pdf…]()

**Comment by josealfredo79** [comment]
[24620193.Sistemas.Numericos.pdf](https://github.com/user-attachments/files/16913387/24620193.Sistemas.Numericos.pdf)

**Comment by YulianaMorales18** [comment]
[Uploading Practica 2.Equipo.pdf…]()

**Comment by LenninGS-0** [comment]
[Practica 2.Equipo Yuli.pdf](https://github.com/user-attachments/files/16913423/Practica.2.Equipo.Yuli.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
