### ISSUE TITLE
Practica de conjuntos 

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-f4#4]
[OperacionesConjuntos practica 2.pdf](https://github.com/user-attachments/files/17123220/OperacionesConjuntos.practica.2.pdf)

**Comment by irwingsael** [comment]
Portada 25/25
Procedimiento 25/25
Figuras, ilustraciones y fotografías. 25/25
Resultados y conclusiones 25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
